import type { Animal, HabitatId } from "./data";

type Entry = [
  id: string,
  name: string,
  english: string,
  latin: string,
  habitat: HabitatId,
  region: string,
  lat: number,
  lng: number,
  status: string,
  diet: string,
  size: string,
  lifespan: string,
  description: string,
  fact: string,
  emoji: string,
  wiki: string,
];
const entries: Entry[] = [
  [
    "snow-leopard",
    "雪豹",
    "Snow Leopard",
    "Panthera uncia",
    "mountain",
    "青海、西藏、新疆等高山地区",
    34.5,
    94.5,
    "VU",
    "肉食性",
    "体长约 0.9–1.3 米（不含尾）",
    "野外约 10–15 年",
    "雪豹在高山岩壁与草甸间活动，以岩羊等有蹄类为食。长尾帮助平衡，宽大的脚掌适应碎石和积雪。",
    "雪豹休息时常用粗长的尾巴护住口鼻，减少热量散失。",
    "🐆",
    "Snow_leopard",
  ],
  [
    "golden-snub-nosed-monkey",
    "川金丝猴",
    "Golden Snub-nosed Monkey",
    "Rhinopithecus roxellana",
    "forest",
    "四川、陕西、甘肃及湖北山林",
    33.5,
    108,
    "EN",
    "以植物为主",
    "体长约 57–76 厘米（不含尾）",
    "可活约 20 年以上",
    "川金丝猴生活在季节变化明显的山地森林，冬季常取食地衣。多个家庭单元可组成庞大的群体。",
    "寒冷时，金丝猴会挤在一起休息，以减少热量散失。",
    "🐒",
    "Golden_snub-nosed_monkey",
  ],
  [
    "black-snub-nosed-monkey",
    "滇金丝猴",
    "Black Snub-nosed Monkey",
    "Rhinopithecus bieti",
    "forest",
    "云南西北部、西藏东南部",
    28,
    99.2,
    "EN",
    "以地衣和植物为主",
    "体长约 50–83 厘米（不含尾）",
    "寿命资料有限",
    "滇金丝猴生活在高海拔针叶林，是分布海拔很高的灵长类。完整森林为群体提供食物与迁移通道。",
    "地衣是滇金丝猴的重要食物，在冬季尤其关键。",
    "🐒",
    "Black_snub-nosed_monkey",
  ],
  [
    "white-headed-langur",
    "白头叶猴",
    "White-headed Langur",
    "Trachypithecus leucocephalus",
    "forest",
    "广西崇左喀斯特地区",
    22.4,
    107.5,
    "CR",
    "草食性",
    "体重约 6–9 千克",
    "寿命资料有限",
    "白头叶猴仅自然分布于广西一小片石灰岩山地。它们白天在林中取食，夜间常利用岩壁洞穴休息。",
    "幼猴出生时毛色偏金黄，随成长逐渐变为成年个体的黑白色。",
    "🐒",
    "White-headed_langur",
  ],
  [
    "asian-elephant",
    "亚洲象",
    "Asian Elephant",
    "Elephas maximus",
    "forest",
    "云南西双版纳、普洱等地",
    22.1,
    100.9,
    "EN",
    "草食性",
    "体重约 2–5 吨",
    "可活约 60 年",
    "亚洲象在森林与开阔地之间移动，以草、树叶、树皮和果实为食。雌象及幼象组成家庭群，需要连通的栖息地。",
    "亚洲象鼻端通常有一个指状突起，非洲象则有两个。",
    "🐘",
    "Asian_elephant",
  ],
  [
    "asiatic-black-bear",
    "亚洲黑熊",
    "Asiatic Black Bear",
    "Ursus thibetanus",
    "forest",
    "东北、西南及中部山林",
    30.5,
    102.8,
    "VU",
    "杂食性",
    "体重约 50–200 千克",
    "野外约 20–25 年",
    "亚洲黑熊胸前通常有浅色月牙斑，善于爬树。果实、坚果和昆虫都是食物，食性会随季节而改变。",
    "黑熊取食果实后能通过粪便传播种子。",
    "🐻",
    "Asian_black_bear",
  ],
  [
    "takin",
    "羚牛",
    "Takin",
    "Budorcas taxicolor",
    "mountain",
    "秦岭及西南山地",
    33.8,
    107.7,
    "VU",
    "草食性",
    "体重约 200–350 千克",
    "可活约 15–20 年",
    "羚牛在山地森林与高山草甸间季节性移动，以叶片、嫩枝和草本植物为食。粗壮的四肢适应陡峭山坡。",
    "羚牛虽名字带牛，却属于牛科中的羊亚科。",
    "🐐",
    "Takin",
  ],
  [
    "tibetan-antelope",
    "藏羚",
    "Tibetan Antelope",
    "Pantholops hodgsonii",
    "mountain",
    "西藏、青海、新疆高原",
    35.2,
    89.4,
    "NT",
    "草食性",
    "体重约 25–40 千克",
    "野外约 8–10 年",
    "藏羚生活在寒冷高原的开阔荒原与草地，部分雌性会迁往集中产仔地。保护迁徙通道对种群恢复十分重要。",
    "雄性藏羚长有细长的角，雌性通常无角。",
    "🦌",
    "Tibetan_antelope",
  ],
  [
    "kiang",
    "藏野驴",
    "Kiang",
    "Equus kiang",
    "mountain",
    "青藏高原草原",
    32.5,
    86.5,
    "LC",
    "草食性",
    "肩高约 1.2–1.4 米",
    "可活约 20 年",
    "藏野驴奔跑在高海拔草原，以草和莎草为食。红褐色背部与白色腹部形成醒目的对比。",
    "藏野驴是现存体型最大的野驴。",
    "🫏",
    "Kiang",
  ],
  [
    "przewalskis-horse",
    "普氏野马",
    "Przewalski's Horse",
    "Equus ferus",
    "savanna",
    "新疆、甘肃等重引入地区",
    45.2,
    89,
    "EN",
    "草食性",
    "肩高约 1.2–1.5 米",
    "可活约 20–25 年",
    "普氏野马曾在野外消失，经过圈养繁育和重引入，重新回到部分草原与荒漠。中国的保护项目也参与了这一恢复过程。",
    "普氏野马有直立的短鬃，外形与多数家马不同。",
    "🐎",
    "Przewalski's_horse",
  ],
  [
    "wild-yak",
    "野牦牛",
    "Wild Yak",
    "Bos mutus",
    "mountain",
    "青藏高原高寒地区",
    35,
    85,
    "VU",
    "草食性",
    "雄性体重可超过 800 千克",
    "野外约 20 年",
    "野牦牛在寒冷而稀薄的高原空气中生活，厚毛和强健体格帮助抵御严寒。它们取食高山草甸与草原植物。",
    "野牦牛与常见的家牦牛不同，野外种群需要专门保护。",
    "🦬",
    "Wild_yak",
  ],
  [
    "bharal",
    "岩羊",
    "Bharal",
    "Pseudois nayaur",
    "mountain",
    "青藏高原及周边山地",
    31.5,
    97,
    "LC",
    "草食性",
    "体重约 35–75 千克",
    "野外约 12–15 年",
    "岩羊在陡峭山坡与高山草甸之间觅食，灰蓝色体毛在岩石背景下不易察觉。它们是雪豹的重要猎物。",
    "岩羊虽然叫羊，其形态兼具绵羊和山羊的一些特点。",
    "🐐",
    "Bharal",
  ],
  [
    "tibetan-fox",
    "藏狐",
    "Tibetan Fox",
    "Vulpes ferrilata",
    "mountain",
    "青藏高原草地",
    34,
    98,
    "LC",
    "肉食性",
    "体长约 60–70 厘米（不含尾）",
    "野外寿命资料有限",
    "藏狐在高原开阔地带寻找鼠兔等小型动物。蓬松的颊部毛发和较窄的眼睛形成独特外貌。",
    "鼠兔是藏狐的重要食物，草原中的小型动物支撑着高原食物网。",
    "🦊",
    "Tibetan_fox",
  ],
  [
    "pallas-cat",
    "兔狲",
    "Pallas's Cat",
    "Otocolobus manul",
    "mountain",
    "青藏高原、内蒙古及新疆等地",
    37,
    99,
    "LC",
    "肉食性",
    "体重约 2.5–5 千克",
    "野外寿命资料有限",
    "兔狲利用岩缝和其他动物的洞穴藏身，以鼠兔、啮齿类等为食。浓密毛皮适应寒冷，低而圆的耳朵有利于隐蔽。",
    "兔狲的瞳孔收缩时仍呈圆形，与家猫常见的竖缝不同。",
    "🐈",
    "Pallas's_cat",
  ],
  [
    "chinese-pangolin",
    "中华穿山甲",
    "Chinese Pangolin",
    "Manis pentadactyla",
    "forest",
    "中国南方及邻近地区",
    26,
    117,
    "CR",
    "食蚁性",
    "体长约 40–60 厘米（不含尾）",
    "野外寿命资料有限",
    "中华穿山甲夜间活动，用前爪挖开蚁巢，再以细长黏舌取食。非法捕猎和栖息地丧失使野生种群大幅减少。",
    "穿山甲的鳞片主要由角蛋白构成，与人的指甲成分相近。",
    "🐾",
    "Chinese_pangolin",
  ],
  [
    "masked-palm-civet",
    "果子狸",
    "Masked Palm Civet",
    "Paguma larvata",
    "forest",
    "中国中南部山林",
    29,
    118,
    "LC",
    "杂食性",
    "体长约 50–75 厘米（不含尾）",
    "圈养可超过 15 年",
    "果子狸是善于攀爬的夜行兽，食谱包括果实、小动物和昆虫。额鼻间的白色条纹是辨认它的线索。",
    "果子狸虽然名字带狸，却属于灵猫科，并不是猫科动物。",
    "🐾",
    "Masked_palm_civet",
  ],
  [
    "leopard-cat",
    "豹猫",
    "Leopard Cat",
    "Prionailurus bengalensis",
    "forest",
    "中国东北至华南多地",
    27,
    110,
    "LC",
    "肉食性",
    "体长约 40–65 厘米（不含尾）",
    "野外约 4–10 年",
    "豹猫体型接近家猫，身披斑点，常在森林、灌丛和林缘夜行。它捕食啮齿类等小动物，也擅长攀爬。",
    "豹猫是独立的野生猫科物种，不能当作家猫捕捉或饲养。",
    "🐈",
    "Leopard_cat",
  ],
  [
    "crested-ibis",
    "朱鹮",
    "Crested Ibis",
    "Nipponia nippon",
    "wetland",
    "陕西及多地恢复种群",
    33.2,
    107.5,
    "EN",
    "肉食性 · 水生小动物",
    "体长约 75 厘米",
    "可活约 20 年以上",
    "朱鹮以弯曲长喙在浅水与泥地中觅食，在高树上筑巢。保护与繁育使这一曾极度稀少的鸟类逐渐恢复。",
    "朱鹮展开双翼时，能看到羽毛下方淡淡的粉红色。",
    "🐦",
    "Crested_ibis",
  ],
  [
    "black-necked-crane",
    "黑颈鹤",
    "Black-necked Crane",
    "Grus nigricollis",
    "wetland",
    "青藏高原及云贵高原湿地",
    29.5,
    91,
    "NT",
    "杂食性",
    "身高约 1.1–1.4 米",
    "可活约 20–30 年",
    "黑颈鹤在高原湿地繁殖，冬季前往较低海拔河谷与湖泊。沼泽、草甸及农田共同构成部分种群的生活空间。",
    "黑颈鹤是典型的高原鹤类，能在海拔数千米的湿地繁殖。",
    "🐦",
    "Black-necked_crane",
  ],
  [
    "reeves-pheasant",
    "白冠长尾雉",
    "Reeves's Pheasant",
    "Syrmaticus reevesii",
    "forest",
    "中国中部山地森林",
    31.5,
    112,
    "VU",
    "杂食性",
    "雄性全长可超过 2 米（含尾）",
    "野外寿命资料有限",
    "白冠长尾雉雄鸟有黑白相间的头部和极长尾羽，活动于山地森林与灌丛。它在地面取食，也在树上夜栖。",
    "雄鸟的尾羽占全长很大比例，雌鸟则较短且颜色低调。",
    "🐦",
    "Reeves's_pheasant",
  ],
  [
    "mandarin-duck",
    "鸳鸯",
    "Mandarin Duck",
    "Aix galericulata",
    "wetland",
    "东北繁殖、东部及南方越冬",
    46,
    129,
    "LC",
    "杂食性",
    "体长约 40–50 厘米",
    "野外寿命因环境而异",
    "鸳鸯偏好林木环绕的河流与湖泊，常在树洞筑巢。雄鸟繁殖羽华丽，雌鸟以灰褐色为主。",
    "幼鸟离巢时会从高处树洞跃下，跟随母鸟前往水面。",
    "🦆",
    "Mandarin_duck",
  ],
  [
    "chinese-alligator",
    "扬子鳄",
    "Chinese Alligator",
    "Alligator sinensis",
    "wetland",
    "安徽等长江下游地区",
    30.9,
    118.7,
    "CR",
    "肉食性",
    "全长通常约 1.5–2 米",
    "可活 50 年以上",
    "扬子鳄生活在池塘、沟渠和缓流湿地，冬季进入洞穴休眠。野外种群稀少，栖息地恢复与重引入是保护重点。",
    "扬子鳄是现存两种短吻鳄之一，另一种是美洲短吻鳄。",
    "🐊",
    "Chinese_alligator",
  ],
  [
    "chinese-sturgeon",
    "中华鲟",
    "Chinese Sturgeon",
    "Acipenser sinensis",
    "wetland",
    "长江及中国近海",
    30.7,
    111.3,
    "CR",
    "肉食性 · 底栖动物",
    "大型成鱼可超过 3 米",
    "可活数十年",
    "中华鲟在海洋生长，成熟后回到河流繁殖。水坝、水文变化和栖息地退化使自然繁殖面临严峻困难。",
    "中华鲟体表排列着骨板，骨骼系统保留了大量软骨。",
    "🐟",
    "Chinese_sturgeon",
  ],
  [
    "chinese-white-dolphin",
    "中华白海豚",
    "Indo-Pacific Humpback Dolphin",
    "Sousa chinensis",
    "ocean",
    "珠江口、厦门及华南沿岸",
    22.2,
    113.8,
    "VU",
    "肉食性 · 鱼类",
    "体长约 2–3 米",
    "可活约 30–40 年",
    "中华白海豚是印度太平洋驼海豚的常用中文名，常在河口与近岸浅海活动。船舶噪声、误捕和海岸开发影响它们的生存。",
    "体色会随年龄和地区变化，幼体常为灰色，部分成年个体呈白色或粉红色。",
    "🐬",
    "Indo-Pacific_humpback_dolphin",
  ],
  [
    "yangtze-finless-porpoise",
    "长江江豚",
    "Yangtze Finless Porpoise",
    "Neophocaena asiaeorientalis",
    "wetland",
    "长江中下游、鄱阳湖和洞庭湖",
    29.2,
    116.2,
    "CR",
    "肉食性 · 鱼类",
    "体长约 1.2–1.9 米",
    "可活约 20 年",
    "长江江豚是适应淡水生活的小型鲸类，依靠回声定位寻找猎物。长江禁捕、水域保护与迁地保护共同帮助种群恢复。",
    "江豚没有明显背鳍，背部只有较低的隆起。",
    "🐬",
    "Yangtze_finless_porpoise",
  ],
];
const statusNames: Record<string, string> = {
  LC: "无危",
  NT: "近危",
  VU: "易危",
  EN: "濒危",
  CR: "极危",
};
const photoPositions: Record<string, string> = {
  "golden-snub-nosed-monkey": "50% 15%",
  "asiatic-black-bear": "50% 15%",
  takin: "50% 35%",
  "chinese-sturgeon": "75% 50%",
};
export const chinaAnimals: Animal[] = entries.map(
  ([
    id,
    name,
    english,
    latin,
    habitat,
    region,
    lat,
    lng,
    statusCode,
    diet,
    size,
    lifespan,
    description,
    fact,
    emoji,
    wiki,
  ]) => ({
    id,
    name,
    english,
    latin,
    habitat,
    region: `中国 · ${region}`,
    lat,
    lng,
    statusCode,
    status: statusNames[statusCode],
    diet,
    size,
    lifespan,
    description,
    fact,
    emoji,
    wiki,
    color: "#aaa08c",
    imagePosition: photoPositions[id],
    china: { lat, lng, region },
  }),
);

// Representative observation sites for existing species with a Chinese range.
export const chinaObservations: Record<
  string,
  { lat: number; lng: number; region: string }
> = {
  panda: { lat: 30.7, lng: 103.1, region: "四川、陕西、甘肃山地竹林" },
  tiger: { lat: 43.2, lng: 130.5, region: "吉林、黑龙江等东北林区" },
  redfox: { lat: 40.5, lng: 115, region: "中国北方及高原等地" },
  "brown-bear": { lat: 48, lng: 87, region: "新疆、东北和青藏高原等地" },
  camel: { lat: 40.5, lng: 92.5, region: "新疆、甘肃荒漠" },
  otter: { lat: 25.5, lng: 119.5, region: "中国多地河流及沿岸" },
  crane: { lat: 47.2, lng: 124.2, region: "东北繁殖、江苏等地越冬" },
  leopard: { lat: 37, lng: 111.5, region: "华北及西南山地等地" },
  "red-panda": { lat: 28.3, lng: 96, region: "西藏东南部及邻近山林" },
  "gray-wolf": { lat: 44, lng: 112, region: "内蒙古、新疆及青藏高原等地" },
  "eurasian-lynx": { lat: 49, lng: 121, region: "东北、新疆及青藏高原等地" },
  "common-kingfisher": { lat: 30.2, lng: 120, region: "中国多地河流与池塘" },
  "sea-turtle": { lat: 22.5, lng: 114.9, region: "南海、东海等海域" },
  "whale-shark": { lat: 18, lng: 111.5, region: "南海等暖水海域" },
  "eurasian-beaver": { lat: 46.5, lng: 90.5, region: "新疆乌伦古河流域" },
  "great-white-pelican": { lat: 47, lng: 87.5, region: "新疆等地湖泊" },
  dolphin: { lat: 24, lng: 118.5, region: "中国东南沿海等海域" },
};
