import { additionalAnimals } from "./additionalAnimals";
import { chinaAnimals, chinaObservations } from "./chinaAnimals";
import { assetPath } from "./assets";

export type HabitatId =
  "all" | "savanna" | "forest" | "ocean" | "polar" | "desert" | "wetland" | "mountain";
export type AnimalShape =
  | "cat"
  | "elephant"
  | "giraffe"
  | "hoof"
  | "bear"
  | "wolf"
  | "ape"
  | "whale"
  | "shark"
  | "dolphin"
  | "turtle"
  | "ray"
  | "bird"
  | "penguin"
  | "camel"
  | "crocodile"
  | "otter";
export interface Animal {
  id: string;
  name: string;
  english: string;
  latin: string;
  habitat: HabitatId;
  region: string;
  lat: number;
  lng: number;
  status: string;
  statusCode: string;
  diet: string;
  size: string;
  lifespan: string;
  description: string;
  fact: string;
  shape?: AnimalShape;
  emoji?: string;
  imagePosition?: string;
  color: string;
  wiki: string;
  china?: { lat: number; lng: number; region: string };
}
export const habitats: {
  id: HabitatId;
  name: string;
  english: string;
  caption: string;
  image: string;
}[] = [
  { id: "mountain", name: "高山与高原", english: "MOUNTAIN", caption: "高海拔生命", image: "mountain" },
  {
    id: "savanna",
    name: "草原与旷野",
    english: "GRASSLAND",
    caption: "追随大迁徙的脚步",
    image: "savanna",
  },
  {
    id: "forest",
    name: "森林与雨林",
    english: "FOREST",
    caption: "走进绿色的生命秘境",
    image: "forest",
  },
  {
    id: "ocean",
    name: "海洋与珊瑚礁",
    english: "OCEAN",
    caption: "潜入另一片蓝色星空",
    image: "ocean",
  },
  {
    id: "polar",
    name: "极地与冰原",
    english: "POLAR",
    caption: "邂逅冰雪中的生存者",
    image: "polar",
  },
  {
    id: "desert",
    name: "沙漠与荒漠",
    english: "DESERT",
    caption: "发现极境中的生命力",
    image: "desert",
  },
  {
    id: "wetland",
    name: "湿地与河流",
    english: "WETLAND",
    caption: "聆听水与生命的交响",
    image: "wetland",
  },
];
// Conservation categories are global IUCN categories, not local population assessments.
export const animals: Animal[] = [
  // The original collection includes local schematic models.
  {
    id: "lion",
    name: "非洲狮",
    english: "African Lion",
    latin: "Panthera leo",
    habitat: "savanna",
    region: "非洲 · 撒哈拉以南",
    lat: -2,
    lng: 35,
    status: "易危",
    statusCode: "VU",
    diet: "肉食性",
    size: "体长 1.4–2.5 米",
    lifespan: "野外约 10–14 年",
    description:
      "暮色降临，低沉的吼声掠过金色草原。狮是唯一常以稳定群体生活的猫科动物，雌狮协作狩猎、共同抚育幼崽，狮群的羁绊是它们生存的力量。",
    fact: "狮子的吼声在适宜条件下可以传播约 8 公里，既用于联系伙伴，也用于宣示领地。",
    shape: "cat",
    color: "#bd9258",
    wiki: "Lion",
  },
  {
    id: "elephant",
    name: "非洲草原象",
    english: "African Bush Elephant",
    latin: "Loxodonta africana",
    habitat: "savanna",
    region: "非洲 · 东部与南部",
    lat: -15,
    lng: 25,
    status: "濒危",
    statusCode: "EN",
    diet: "植食性",
    size: "肩高 3–4 米",
    lifespan: "约 60–70 年",
    description:
      "非洲草原象是现存体型最大的陆生动物。象群通常由经验丰富的雌象带领，它们塑造林地、传播种子，为其他生命创造空间。",
    fact: "象能利用低频声音交流，也能感知通过地面传播的震动。",
    shape: "elephant",
    color: "#827e73",
    wiki: "African_bush_elephant",
  },
  {
    id: "giraffe",
    name: "长颈鹿",
    english: "Giraffe",
    latin: "Giraffa camelopardalis",
    habitat: "savanna",
    region: "非洲 · 稀树草原",
    lat: 6,
    lng: 20,
    status: "易危",
    statusCode: "VU",
    diet: "植食性",
    size: "身高 4.3–5.7 米",
    lifespan: "野外约 20–25 年",
    description:
      "长颈鹿用灵巧的长舌采食高处的树叶，斑纹如同独一无二的指纹。它们的身高让它们能观察远方，也避开了与其他食草动物的部分竞争。",
    fact: "和人类一样，长颈鹿通常只有 7 块颈椎，只是每一块都长得多。",
    shape: "giraffe",
    color: "#c69b5e",
    wiki: "Giraffe",
  },
  {
    id: "zebra",
    name: "平原斑马",
    english: "Plains Zebra",
    latin: "Equus quagga",
    habitat: "savanna",
    region: "非洲 · 东部草原",
    lat: -5,
    lng: 31,
    status: "近危",
    statusCode: "NT",
    diet: "植食性",
    size: "体长 2.2–2.5 米",
    lifespan: "野外约 20 年",
    description:
      "黑白条纹在草海中流动，斑马是非洲大迁徙的主角之一。它们能啃食较粗硬的草，为随后到来的其他食草动物打开道路。",
    fact: "实验研究发现，斑马条纹能够减少部分叮咬蝇落到身上的机会。",
    shape: "hoof",
    color: "#dbd8ca",
    wiki: "Plains_zebra",
  },
  {
    id: "cheetah",
    name: "猎豹",
    english: "Cheetah",
    latin: "Acinonyx jubatus",
    habitat: "savanna",
    region: "非洲 · 开阔草原",
    lat: -21,
    lng: 19,
    status: "易危",
    statusCode: "VU",
    diet: "肉食性",
    size: "体长 1.1–1.5 米",
    lifespan: "野外约 10–12 年",
    description:
      "轻盈的骨架、柔韧的脊柱和修长的腿，让猎豹成为陆地上的短跑高手。它们依靠短距离爆发追上猎物，长尾则帮助高速转弯。",
    fact: "猎豹脸上的黑色「泪痕」是它最容易辨认的特征之一。",
    shape: "cat",
    color: "#caa567",
    wiki: "Cheetah",
  },
  {
    id: "rhino",
    name: "白犀",
    english: "White Rhinoceros",
    latin: "Ceratotherium simum",
    habitat: "savanna",
    region: "非洲 · 南部草原",
    lat: -26,
    lng: 28,
    status: "近危",
    statusCode: "NT",
    diet: "植食性",
    size: "体长 3.4–4.2 米",
    lifespan: "约 40–50 年",
    description:
      "白犀用宽阔平直的嘴唇像割草机一样采食地面青草。厚重的身躯之下，是对栖息地和种群保护高度依赖的生命。",
    fact: "犀牛角主要由角蛋白组成，与人的头发和指甲含有相同类型的结构蛋白。",
    shape: "hoof",
    color: "#8b887d",
    wiki: "White_rhinoceros",
  },
  {
    id: "tiger",
    name: "虎",
    english: "Tiger",
    latin: "Panthera tigris",
    habitat: "forest",
    region: "亚洲 · 森林与草地",
    lat: 24,
    lng: 84,
    status: "濒危",
    statusCode: "EN",
    diet: "肉食性",
    size: "体长 1.4–2.8 米",
    lifespan: "野外约 10–15 年",
    description:
      "虎独自穿行于林间，条纹将轮廓融入斑驳的光影。作为顶级捕食者，它的存在往往意味着森林仍能支持完整的食物网。",
    fact: "虎是出色的游泳者，炎热时常在水中降温。",
    shape: "cat",
    color: "#cb8035",
    wiki: "Tiger",
  },
  {
    id: "panda",
    name: "大熊猫",
    english: "Giant Panda",
    latin: "Ailuropoda melanoleuca",
    habitat: "forest",
    region: "亚洲 · 中国山地竹林",
    lat: 31,
    lng: 103,
    status: "易危",
    statusCode: "VU",
    diet: "以竹类为主",
    size: "体长 1.2–1.9 米",
    lifespan: "野外约 15–20 年",
    description:
      "云雾缭绕的山地竹林中，大熊猫每天花大量时间进食。它保留了食肉目动物的消化系统，却演化出以竹子为主的独特生活方式。",
    fact: "大熊猫的「第六根手指」其实是增大的腕骨，帮助它握住竹竿。",
    shape: "bear",
    color: "#e4e1d8",
    wiki: "Giant_panda",
  },
  {
    id: "gorilla",
    name: "西部大猩猩",
    english: "Western Gorilla",
    latin: "Gorilla gorilla",
    habitat: "forest",
    region: "非洲 · 中西部雨林",
    lat: 1,
    lng: 12,
    status: "极危",
    statusCode: "CR",
    diet: "以植物为主",
    size: "站立高约 1.3–1.8 米",
    lifespan: "约 35–40 年",
    description:
      "西部大猩猩在浓密雨林中以家庭群体生活，采食果实、叶片和茎。它们传播种子，也是森林更新的重要参与者。",
    fact: "每只大猩猩的鼻纹都具有个体特征，研究者可以据此识别它们。",
    shape: "ape",
    color: "#494640",
    wiki: "Western_gorilla",
  },
  {
    id: "orangutan",
    name: "婆罗洲猩猩",
    english: "Bornean Orangutan",
    latin: "Pongo pygmaeus",
    habitat: "forest",
    region: "亚洲 · 婆罗洲",
    lat: 1,
    lng: 114,
    status: "极危",
    statusCode: "CR",
    diet: "以果实为主",
    size: "体长约 1–1.4 米",
    lifespan: "野外约 35–45 年",
    description:
      "红褐色身影在树冠间缓慢移动，婆罗洲猩猩几乎把整个生活安放在树上。森林破碎化正让它们的家园不断缩小。",
    fact: "猩猩会把树枝弯折、编织成巢，通常每晚制作新的睡巢。",
    shape: "ape",
    color: "#a2542f",
    wiki: "Bornean_orangutan",
  },
  {
    id: "redfox",
    name: "赤狐",
    english: "Red Fox",
    latin: "Vulpes vulpes",
    habitat: "forest",
    region: "北半球 · 林地与开阔地",
    lat: 49,
    lng: 15,
    status: "无危",
    statusCode: "LC",
    diet: "杂食性",
    size: "体长 45–90 厘米",
    lifespan: "野外通常 3–5 年",
    description:
      "赤狐拥有灵敏的听觉和惊人的适应能力。从森林边缘到城市绿地，它们总能找到食物与藏身之处。",
    fact: "捕捉雪下的小型哺乳动物时，赤狐会高高跃起，再头朝下扎入雪中。",
    shape: "wolf",
    color: "#bb6537",
    wiki: "Red_fox",
  },
  {
    id: "brown-bear",
    name: "棕熊",
    english: "Brown Bear",
    latin: "Ursus arctos",
    habitat: "forest",
    region: "北美洲与欧亚大陆",
    lat: 58,
    lng: -125,
    status: "无危",
    statusCode: "LC",
    diet: "杂食性",
    size: "体长 1.4–2.8 米",
    lifespan: "野外约 20–30 年",
    description:
      "棕熊穿行于针叶林、河谷和山地，食谱随季节变化。浆果、根茎、昆虫与鱼类都可能成为它们储备能量的来源。",
    fact: "冬眠期间棕熊的心率和代谢会显著降低，依靠脂肪储备度过食物短缺的季节。",
    shape: "bear",
    color: "#73553c",
    wiki: "Brown_bear",
  },
  {
    id: "blue-whale",
    name: "蓝鲸",
    english: "Blue Whale",
    latin: "Balaenoptera musculus",
    habitat: "ocean",
    region: "全球 · 开阔海洋",
    lat: -25,
    lng: -25,
    status: "濒危",
    statusCode: "EN",
    diet: "主要为磷虾",
    size: "体长约 24–30 米",
    lifespan: "约 80–90 年",
    description:
      "蓝鲸在深蓝中缓缓滑行，是已知地球历史上体型最大的动物。它以微小的磷虾为食，在广袤大洋间迁徙，以低沉的声音彼此联系。",
    fact: "蓝鲸的心脏可以重达数百千克，却以非常缓慢的节律支持深潜时的生命活动。",
    shape: "whale",
    color: "#66878e",
    wiki: "Blue_whale",
  },
  {
    id: "orca",
    name: "虎鲸",
    english: "Orca",
    latin: "Orcinus orca",
    habitat: "ocean",
    region: "全球 · 近海与远洋",
    lat: 47,
    lng: -132,
    status: "数据缺乏",
    statusCode: "DD",
    diet: "肉食性",
    size: "体长约 5–9 米",
    lifespan: "数十年，雌性通常更长",
    description:
      "虎鲸拥有复杂的社会联系，不同群体发展出各自的食谱和捕猎传统。黑白身影下，是高度协作的海洋家族。",
    fact: "不同虎鲸家族拥有可以代代相传的独特叫声组合，类似各自的「方言」。",
    shape: "whale",
    color: "#252e31",
    wiki: "Orca",
  },
  {
    id: "dolphin",
    name: "宽吻海豚",
    english: "Common Bottlenose Dolphin",
    latin: "Tursiops truncatus",
    habitat: "ocean",
    region: "全球 · 温带与热带海域",
    lat: 25,
    lng: -75,
    status: "无危",
    statusCode: "LC",
    diet: "鱼类与头足类",
    size: "体长约 2–4 米",
    lifespan: "约 40–60 年",
    description:
      "宽吻海豚用回声定位感知水下环境，灵活协作捕食。它们的社会关系不断变化，交流方式也远比表面看起来丰富。",
    fact: "宽吻海豚能够发出具有个体特征的「签名哨声」。",
    shape: "dolphin",
    color: "#8ca3aa",
    wiki: "Common_bottlenose_dolphin",
  },
  {
    id: "whale-shark",
    name: "鲸鲨",
    english: "Whale Shark",
    latin: "Rhincodon typus",
    habitat: "ocean",
    region: "全球 · 热带暖水海域",
    lat: 9,
    lng: 65,
    status: "濒危",
    statusCode: "EN",
    diet: "浮游生物与小鱼",
    size: "常见体长 6–12 米",
    lifespan: "可能超过 80 年",
    description:
      "星点般的斑纹覆盖着鲸鲨庞大的身体。作为现存最大的鱼类，它以滤食方式获取微小食物，缓慢巡游于温暖海域。",
    fact: "鲸鲨鳃部后方的斑点排列可用于照片识别，帮助研究者追踪个体。",
    shape: "shark",
    color: "#4b7882",
    wiki: "Whale_shark",
  },
  {
    id: "sea-turtle",
    name: "绿海龟",
    english: "Green Sea Turtle",
    latin: "Chelonia mydas",
    habitat: "ocean",
    region: "全球 · 热带与亚热带海域",
    lat: -12,
    lng: 145,
    status: "无危",
    statusCode: "LC",
    diet: "成体以海草、藻类为主",
    size: "背甲长约 80–120 厘米",
    lifespan: "可超过 60 年",
    description:
      "绿海龟穿梭在海草床与珊瑚礁之间，成熟后能远距离迁徙回到繁殖地。海滩、沿岸浅海与大洋，共同组成它的一生。",
    fact: "2025 年全球评估将绿海龟下调为无危，但不同区域种群仍面临显著威胁。",
    shape: "turtle",
    color: "#7c8560",
    wiki: "Green_sea_turtle",
  },
  {
    id: "manta",
    name: "大洋蝠鲼",
    english: "Giant Oceanic Manta Ray",
    latin: "Mobula birostris",
    habitat: "ocean",
    region: "全球 · 热带与温带海域",
    lat: -8,
    lng: 74,
    status: "濒危",
    statusCode: "EN",
    diet: "浮游生物",
    size: "翼展可达约 7 米",
    lifespan: "可超过 40 年",
    description:
      "大洋蝠鲼展开胸鳍，像飞翔一样掠过海水。它将头部的鳍展开，帮助把富含浮游生物的海水导入口中。",
    fact: "蝠鲼腹部的黑色斑纹因个体而异，是研究者辨认它们的依据。",
    shape: "ray",
    color: "#3e4e55",
    wiki: "Giant_oceanic_manta_ray",
  },
  {
    id: "polar-bear",
    name: "北极熊",
    english: "Polar Bear",
    latin: "Ursus maritimus",
    habitat: "polar",
    region: "北极 · 环北冰洋",
    lat: 74,
    lng: 25,
    status: "易危",
    statusCode: "VU",
    diet: "主要为海豹",
    size: "体长约 1.8–2.8 米",
    lifespan: "野外约 20–25 年",
    description:
      "北极熊依靠海冰寻找海豹，厚脂肪和浓密被毛帮助它抵御严寒。海冰的季节变化，决定了它们的狩猎和休息节律。",
    fact: "北极熊的皮肤是黑色的，被毛本身没有白色色素，视觉上的白色来自光的散射。",
    shape: "bear",
    color: "#e2dfcc",
    wiki: "Polar_bear",
  },
  {
    id: "emperor-penguin",
    name: "帝企鹅",
    english: "Emperor Penguin",
    latin: "Aptenodytes forsteri",
    habitat: "polar",
    region: "南极 · 海冰与沿海",
    lat: -74,
    lng: 30,
    status: "近危",
    statusCode: "NT",
    diet: "鱼类、磷虾与乌贼",
    size: "身高约 1.1–1.2 米",
    lifespan: "野外约 15–20 年",
    description:
      "南极寒冬，雄性帝企鹅将蛋托在脚上，用腹部的育儿袋保护后代。密集的集群不断缓慢移动，让每个成员都有机会取暖。",
    fact: "帝企鹅能够潜入 500 米以上的深度，是潜水能力最强的鸟类之一。",
    shape: "penguin",
    color: "#35434a",
    wiki: "Emperor_penguin",
  },
  {
    id: "arctic-fox",
    name: "北极狐",
    english: "Arctic Fox",
    latin: "Vulpes lagopus",
    habitat: "polar",
    region: "北极 · 苔原",
    lat: 69,
    lng: -35,
    status: "无危",
    statusCode: "LC",
    diet: "杂食性",
    size: "体长约 45–70 厘米",
    lifespan: "野外约 3–6 年",
    description:
      "小巧的耳朵、短吻和浓密冬毛减少了热量流失。许多北极狐随季节换毛，在雪地与夏季苔原之间改变自己的保护色。",
    fact: "北极狐的脚掌也覆盖着毛，既保暖，也有助于在冰雪上行走。",
    shape: "wolf",
    color: "#e1e0d4",
    wiki: "Arctic_fox",
  },
  {
    id: "walrus",
    name: "海象",
    english: "Walrus",
    latin: "Odobenus rosmarus",
    habitat: "polar",
    region: "北极 · 浅海与浮冰",
    lat: 70,
    lng: -162,
    status: "易危",
    statusCode: "VU",
    diet: "主要为底栖软体动物",
    size: "体长约 2.2–3.6 米",
    lifespan: "约 30–40 年",
    description:
      "海象在浅海海底用敏感的胡须寻找食物。长长的獠牙既是社会展示的工具，也能帮助它们爬上冰面。",
    fact: "海象的胡须布满神经末梢，能在浑浊海水中通过触觉寻找贝类。",
    shape: "otter",
    color: "#a38a77",
    wiki: "Walrus",
  },
  {
    id: "reindeer",
    name: "驯鹿",
    english: "Reindeer",
    latin: "Rangifer tarandus",
    habitat: "polar",
    region: "北半球 · 苔原与寒带森林",
    lat: 66,
    lng: 65,
    status: "易危",
    statusCode: "VU",
    diet: "植食性",
    size: "体长约 1.6–2.3 米",
    lifespan: "野外约 10–15 年",
    description:
      "驯鹿的蹄会随季节改变软硬程度，适应湿软苔原与坚硬冰雪。有些种群每年完成极为漫长的陆地迁徙。",
    fact: "在鹿科动物中，驯鹿是通常雌雄都会长角的物种。",
    shape: "hoof",
    color: "#a3947e",
    wiki: "Reindeer",
  },
  {
    id: "snowy-owl",
    name: "雪鸮",
    english: "Snowy Owl",
    latin: "Bubo scandiacus",
    habitat: "polar",
    region: "北极 · 开阔苔原",
    lat: 68,
    lng: 105,
    status: "易危",
    statusCode: "VU",
    diet: "肉食性",
    size: "翼展约 1.3–1.5 米",
    lifespan: "野外可超过 10 年",
    description:
      "雪鸮在无遮蔽的北极苔原筑巢，白色羽毛帮助它融入雪景。它们能在白昼捕猎，尤其依赖旅鼠等小型哺乳动物。",
    fact: "雪鸮的脚趾覆有厚羽，像天然的保暖靴。",
    shape: "bird",
    color: "#dddcd0",
    wiki: "Snowy_owl",
  },
  {
    id: "fennec",
    name: "耳廓狐",
    english: "Fennec Fox",
    latin: "Vulpes zerda",
    habitat: "desert",
    region: "非洲 · 撒哈拉沙漠",
    lat: 25,
    lng: 8,
    status: "无危",
    statusCode: "LC",
    diet: "杂食性",
    size: "体长约 24–41 厘米",
    lifespan: "野外约 10 年",
    description:
      "巨大耳朵是耳廓狐的标志，也帮助散热和捕捉细微声响。白天躲进沙下洞穴，夜间才是它们探索荒漠的时间。",
    fact: "耳廓狐是体型最小的犬科动物，脚底的毛能隔开滚烫的沙地。",
    shape: "wolf",
    color: "#d8bd87",
    wiki: "Fennec_fox",
  },
  {
    id: "camel",
    name: "野双峰驼",
    english: "Wild Camel",
    latin: "Camelus ferus",
    habitat: "desert",
    region: "亚洲 · 中国与蒙古荒漠",
    lat: 42,
    lng: 94,
    status: "极危",
    statusCode: "CR",
    diet: "植食性",
    size: "肩高约 1.8–2.3 米",
    lifespan: "约 40 年",
    description:
      "野双峰驼是真正的野生物种，与家养双峰驼不同。它们在极端干旱、温差巨大的荒漠里长距离行走，寻找稀疏的植物和水源。",
    fact: "驼峰储存的是脂肪，而不是水；脂肪可以在食物短缺时提供能量。",
    shape: "camel",
    color: "#b1986c",
    wiki: "Wild_Bactrian_camel",
  },
  {
    id: "meerkat",
    name: "细尾獴",
    english: "Meerkat",
    latin: "Suricata suricatta",
    habitat: "desert",
    region: "非洲 · 南部干旱地区",
    lat: -25,
    lng: 21,
    status: "无危",
    statusCode: "LC",
    diet: "以昆虫等小动物为主",
    size: "体长约 25–35 厘米",
    lifespan: "野外约 6–8 年",
    description:
      "细尾獴家族在沙地中忙碌觅食，总有成员站起身警戒。复杂的叫声帮助它们向同伴传递危险的类型和距离。",
    fact: "成年细尾獴会逐步改变提供给幼崽的蝎子的状态，帮助幼崽学习处理危险猎物。",
    shape: "otter",
    color: "#ad966f",
    wiki: "Meerkat",
  },
  {
    id: "oryx",
    name: "阿拉伯大羚羊",
    english: "Arabian Oryx",
    latin: "Oryx leucoryx",
    habitat: "desert",
    region: "亚洲 · 阿拉伯半岛",
    lat: 22,
    lng: 49,
    status: "易危",
    statusCode: "VU",
    diet: "植食性",
    size: "肩高约 1 米",
    lifespan: "约 15–20 年",
    description:
      "白色被毛反射阳光，细长双角划过沙丘的轮廓。阿拉伯大羚羊曾在野外灭绝，保护繁育和放归让它重新回到荒漠。",
    fact: "它是通过保护行动，从「野外灭绝」恢复到「易危」的重要案例。",
    shape: "hoof",
    color: "#e2ddc9",
    wiki: "Arabian_oryx",
  },
  {
    id: "addax",
    name: "旋角羚",
    english: "Addax",
    latin: "Addax nasomaculatus",
    habitat: "desert",
    region: "非洲 · 撒哈拉沙漠",
    lat: 18,
    lng: 12,
    status: "极危",
    statusCode: "CR",
    diet: "植食性",
    size: "肩高约 95–115 厘米",
    lifespan: "约 20 年",
    description:
      "宽大的蹄帮助旋角羚行走在松软沙地上，扭转的长角是它的鲜明特征。如今野外种群极为稀少，保护工作仍十分紧迫。",
    fact: "旋角羚可以从食物中获得大量水分，对极端干旱的环境有很强的适应能力。",
    shape: "hoof",
    color: "#cec8ae",
    wiki: "Addax",
  },
  {
    id: "ostrich",
    name: "非洲鸵鸟",
    english: "Common Ostrich",
    latin: "Struthio camelus",
    habitat: "desert",
    region: "非洲 · 干旱草地与半荒漠",
    lat: 17,
    lng: 24,
    status: "无危",
    statusCode: "LC",
    diet: "杂食性，以植物为主",
    size: "身高约 2–2.8 米",
    lifespan: "野外约 30–40 年",
    description:
      "鸵鸟不会飞，但强壮的双腿足以让它在开阔地快速奔跑。长颈和敏锐的视力帮助它发现远处的危险。",
    fact: "鸵鸟每只脚只有两根脚趾，这种结构有利于高速奔跑。",
    shape: "bird",
    color: "#49453f",
    wiki: "Common_ostrich",
  },
  {
    id: "flamingo",
    name: "大红鹳",
    english: "Greater Flamingo",
    latin: "Phoenicopterus roseus",
    habitat: "wetland",
    region: "非洲、南欧与南亚 · 浅水湿地",
    lat: 37,
    lng: 22,
    status: "无危",
    statusCode: "LC",
    diet: "小型水生生物",
    size: "身高约 1.1–1.5 米",
    lifespan: "可超过 30 年",
    description:
      "大红鹳在浅水中倒置头部，用特化的喙过滤食物。成群的粉色身影把盐湖和河口变成流动的风景。",
    fact: "红鹳羽毛的粉色来自食物中的类胡萝卜素，并不是天生就如此鲜艳。",
    shape: "bird",
    color: "#e49e95",
    wiki: "Greater_flamingo",
  },
  {
    id: "hippo",
    name: "河马",
    english: "Hippopotamus",
    latin: "Hippopotamus amphibius",
    habitat: "wetland",
    region: "非洲 · 河流与湖泊",
    lat: -7,
    lng: 22,
    status: "易危",
    statusCode: "VU",
    diet: "主要为草类",
    size: "体长约 3–5 米",
    lifespan: "约 40–50 年",
    description:
      "河马白天在水中避暑，夜间上岸吃草。眼、耳和鼻孔长在头部上方，让它能在身体大部分没入水中时仍观察周围。",
    fact: "河马皮肤分泌的红橙色液体有助于保护皮肤，它并不是血汗。",
    shape: "hoof",
    color: "#85797a",
    wiki: "Hippopotamus",
  },
  {
    id: "crocodile",
    name: "尼罗鳄",
    english: "Nile Crocodile",
    latin: "Crocodylus niloticus",
    habitat: "wetland",
    region: "非洲 · 河流、湖泊与沼泽",
    lat: 12,
    lng: 30,
    status: "无危",
    statusCode: "LC",
    diet: "肉食性",
    size: "体长通常 3–5 米",
    lifespan: "可超过 50 年",
    description:
      "尼罗鳄静伏在水边等待时机，强有力的尾部驱动它在水下前进。尽管外表威严，母鳄会守护巢穴并帮助幼鳄入水。",
    fact: "鳄鱼会轻柔地把刚孵化的幼崽含在嘴里，运送到水中。",
    shape: "crocodile",
    color: "#6e775a",
    wiki: "Nile_crocodile",
  },
  {
    id: "otter",
    name: "欧亚水獭",
    english: "Eurasian Otter",
    latin: "Lutra lutra",
    habitat: "wetland",
    region: "欧亚大陆 · 河流与沿岸",
    lat: 48,
    lng: 55,
    status: "近危",
    statusCode: "NT",
    diet: "主要为鱼类",
    size: "体长约 55–95 厘米",
    lifespan: "野外通常 5–10 年",
    description:
      "欧亚水獭以流线型身体潜入河中，密集的毛发保留空气以维持体温。洁净水体、丰富鱼类和隐蔽岸线是它的生存基础。",
    fact: "水獭会利用粪便中的气味传递信息，标记常用的活动区域。",
    shape: "otter",
    color: "#786350",
    wiki: "Eurasian_otter",
  },
  {
    id: "capybara",
    name: "水豚",
    english: "Capybara",
    latin: "Hydrochoerus hydrochaeris",
    habitat: "wetland",
    region: "南美洲 · 河流与湿地",
    lat: -12,
    lng: -58,
    status: "无危",
    statusCode: "LC",
    diet: "植食性",
    size: "体长约 1–1.3 米",
    lifespan: "野外约 6–10 年",
    description:
      "水豚是现存最大的啮齿动物，常成群生活在水边。半蹼状的脚趾让它游泳自如，遇到危险时会迅速躲入水中。",
    fact: "水豚的眼睛、耳朵和鼻孔都靠近头顶，方便在水中观察和呼吸。",
    shape: "hoof",
    color: "#a58c68",
    wiki: "Capybara",
  },
  {
    id: "crane",
    name: "丹顶鹤",
    english: "Red-crowned Crane",
    latin: "Grus japonensis",
    habitat: "wetland",
    region: "亚洲 · 东部湿地",
    lat: 44,
    lng: 129,
    status: "易危",
    statusCode: "VU",
    diet: "杂食性",
    size: "身高约 1.5 米",
    lifespan: "野外约 20–30 年",
    description:
      "丹顶鹤在沼泽与浅水间优雅行走，成对起舞、对鸣。湿地的连通和季节性水位变化，对它们的繁殖与越冬至关重要。",
    fact: "丹顶鹤头顶的红色部分是裸露的皮肤，而不是红色羽毛。",
    shape: "bird",
    color: "#e2e0d3",
    wiki: "Red-crowned_crane",
  },
];
animals.push(...additionalAnimals);
animals.push(...chinaAnimals);
for (const animal of animals) {
  if (chinaObservations[animal.id]) animal.china = chinaObservations[animal.id];
}
export const habitatName = (id: HabitatId) =>
  habitats.find((h) => h.id === id)?.name ?? "全部环境";
export const imagePath = (id: string) => assetPath(`images/${id}.jpg`);
export const statusColor = (code: string) =>
  ({
    LC: "#b4d39b",
    NT: "#d2c580",
    VU: "#e4b871",
    EN: "#e99571",
    CR: "#e88181",
    DD: "#a3b3bc",
  })[code] ?? "#a3b3bc";
